MVC5_ATM/Controllers/CheckingAccountController.cs
using MVC5_ATM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC5_ATM.Controllers
{
    public class CheckingAccountController : Controller
    {
        private ApplicationDbContext dbContext = new ApplicationDbContext();
        // GET: CheckingAccount/Details/5
        public ActionResult Details()
        {
            var dummyAccount = new CheckingAccount { Id = 1 , AccountNumber="0000666777" , FirstName="Arif" , LastName ="Khan" , Balance=500.66m };
            return View(dummyAccount);
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC5_ATM/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using MVC5_ATM.Models;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using System.Web;

namespace MVC5_ATM.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext dbContext = new ApplicationDbContext();

        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccountId = dbContext.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First().Id;
            ViewBag.CheckingAccountId = checkingAccountId;

            var manager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = manager.FindById(userId);
            var pin = user.Pin;
            ViewBag.Pin = pin;

            return View();
        }

        public ActionResult Serial(string letterCase)
        {
            var serial = "SOMETOPSECRETSERIAL1";
            if (letterCase == "lower")
            {
                return Content(serial.ToLower());
            }

            return Content(serial);
        }
    }
}

MVC5_ATM/Controllers/TransactionController.cs
using MVC5_ATM.Models;
using System.Web.Mvc;

namespace MVC5_ATM.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private ApplicationDbContext dbContext = new ApplicationDbContext(); 

        public ActionResult Deposit(int checkingAccountId)
        {

            return View();
        }

        [HttpPost]
        public ActionResult Deposit(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                dbContext.Transactions.Add(transaction);
                dbContext.SaveChanges();
                return RedirectToAction("Index","Home");
            }
            return View();
        }

    }
}

MVC5_ATM/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC5_ATM/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC5_ATM/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-6 margin-top">
        <a href="#" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-circle-arrow-down"></span> Withdrawal </a>
        <a href="#" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-flash"></span> Quick Cash $100</a>
        <a href="@Url.Action("Details","CheckingAccount")" class="btn btn-primary btn-lg btn-block">
        <span class="glyphicon glyphicon-question-sign"></span>  Balance Inquiry</a>
    </div>
    
    <div class="col-md-6 margin-top">
        <a href="#" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-print"></span> Print Statement</a>
        <a href="#" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-transfer"></span> Transfer Funds</a>
        <a href="@Url.Action("Deposit","Transaction" , new { checkingAccountId = ViewBag.CheckingAccountId })" class="btn btn-primary btn-lg btn-block">
        <span class="glyphicon glyphicon-circle-arrow-up"></span> Deposit </a>
    </div>
</div>

@ViewBag.Pin

You are using @Request.Browser.Browser , and that's ok! Email us at support@mvc.com or send us a tweet @@mvcatm.

@{ var amounts = new List<decimal> { 100, 22.3m, -2, 100 }; }

<ul>
    @foreach (var amount in amounts)
    {

        <li>@formatAmount(amount)</li>

    }
</ul>

    @helper formatAmount(decimal amount)
    {
        var color = "green";
        if (amount < 0)
        {
            color = "red";
        }

        <span style="color: @color">@String.Format("{0:c}",amount)</span>
    }